#Create a new file
File = open("resource.txt","w+")

#Insert data
File.write("log=0\n")
File.write("pebble=0\n")
File.write("plank=0\n")
File.write("stick=0\n")
File.write("cobblestone=0\n")
File.write("iron_ore=0\n")
File.write("gold_ore=0\n")
File.write("iron_ingot=0\n")
File.write("gold_ingot=0\n")
File.write("furnance=False\n")
File.write("wooden_axe=False\n")
File.write("wooden_pick=False\n")
File.write("stone_axe=False\n")
File.write("stone_pick=False\n")
#Phase 2 update
File.write("iron_axe=False\n")
File.write("iron_pick=False\n")
File.write("gold_axe=False\n")
File.write("gold_pick=False\n")
File.write("ruby_ore=0\n")
File.write("sapphire_ore=0\n")
File.write("emerald_ore=0\n")
File.write("ruby_gem=0\n")
File.write("sapphire_gem=0\n")
File.write("emerald_gem=0\n")
File.write("ruby_axe=False\n")
File.write("ruby_pick=False\n")
File.write("sapphire_axe=False\n")
File.write("sapphire_pick=False\n")
File.write("emerald_axe=False\n")
File.write("emerald_pick=False\n")
#Phase 3 update
File.write("chalcocite=0\n")
File.write("bauxite=0\n")
File.write("acanthite=0\n")
File.write("galena=0\n")
File.write("uraninite=0\n")
File.write("copper_ingot=0\n")
File.write("aluminium_ingot=0\n")
File.write("silver_ingot=0\n")
File.write("lead_ingot=0\n")
File.write("uranium=0\n")

#Close file
File.close()